### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by xong** [FurkanToprak/OkapiBM25#1]
Hi,

i would love to use this for another open source project.
Can you add a license to your project, so it is clear, that we can use it?

Best regards,
Robert

**Comment by FurkanToprak** [comment]
@xong Thank you for contacting me! I've added an MIT license. You can go ahead and use it now. If possible, I'd love to see the project as well.

**Comment by xong** [comment]
Hi @FurkanToprak, thank you for your fast response. I used part of your code here: https://github.com/redaxo/redaxo/pull/3966
I think I found a bug in your code. `getTermFrequency` always returns "1". You can have a look on my approach: https://github.com/redaxo/redaxo/pull/3966/commits/154023ecd4c96e500f5865e809eddf0f58dc7527#diff-d6747527bdb2eac9e2dceb8470a2bdb3e7ca4849c7589c8348d49b5f2fe508c4R190
Cya
Robert

**Comment by FurkanToprak** [comment]
Extremely grateful! I must have neglected the global flag. I've pushed
updates.
