### ISSUE TITLE
Provide a utility to sort objects

### ISSUE THREAD

**Issue by azmeuk** [FurkanToprak/OkapiBM25#3]
Hi. Thank you for providing this library. I think there is one utility missing: a function that would take a query, a list of objects, and would sort the objects depending on the query, and a rule to get the interesting data from the object. Something like this:

```javascript
function bm25sort(query, objects, key_func) {
    var keys = objects.map(key_func)
    var scores = BM25.BM25(keys, query)
    var container = [];
    for (var i in scores) {
        container.push({
            obj: objects[i],
            score: scores[i],
        })
    }
    container.sort((a, b) => b.score - a.score)
    return container.map(elt => elt.obj)
}
```
One could use this function like this:
```javascript
var objects = [
    {"id": "foo", "description": "Lorem ipsum dolor sit amet"},
    {"id": "bar", "description": "Abra Kadabra"},
    {"id": "baz", "description": "Abra Alakazam"},
]
bm25sort("Abra", objects, obj => obj.description)
/* returns the objects list, ordered by their bm25 score */
```

What do you think?

**Comment by FurkanToprak** [comment]
I like the idea. Would you like to submit a PR, or should I implement the feature?

**Comment by FurkanToprak** [comment]
Hi @azmeuk, please check out the newest updates. While I love the sorting idea and have incorporated it, I've realized that the attribute extraction feature `obj => obj.description` would probably be better substituted with a `map()` function prior to calling `BM25()`. I think it is a good idea, but probably would make the module less accessible and more confusing for the majority of users. 

Please let me know if you have any objections or want any further improvements. I greatly appreciate your time and PR. Have a great day in Bordeaux, France.

**Comment by FurkanToprak** [comment]
BTW, I'll close this issue if I don't hear back in a week.

**Comment by azmeuk** [comment]
Hi. Thank you for considering this issue :)

I understand you point. I think that letting the users choose the sort function is a good idea.
The main limitation in my opinion is that the `BM25` function does not return the actual objects I need to sort, thus making its usage less straigthforward. As a naive user I don't actually need to know what scores the *documents* have, I just need objects to be sorted.

```typescript
var objects = [
    {"id": "foo", "description": "Lorem ipsum dolor sit amet"},
    {"id": "bar", "description": "Abra Kadabra Abra"},
    {"id": "baz", "description": "Abra Alakazam"},
]
var result = BM25(objects.map(obj => obj.description), ["Abra"], undefined, (firstEl, secondEl) => secondEl.score - firstEl.score)
result
[
  { score: 0.5442147286003254, document: 'Abra Kadabra' },
  { score: 0.5442147286003254, document: 'Abra Alakazam' },
  { score: 0, document: 'Lorem ipsum dolor sit amet' }
]

// This is cool, but now I have to sort the objects by the score of their descriptions
// this i a bit cumbersome :)
var docs_scores = Object.fromEntries(result.map(item => [item.document, item.score]))
objects.sort((item1, item2) => docs_scores[item2.description] - docs_scores[item1.description])
[
  { id: 'bar', description: 'Abra Kadabra Abra' },
  { id: 'baz', description: 'Abra Alakazam' },
  { id: 'foo', description: 'Lorem ipsum dolor sit amet' }
]
// and THIS is the result I am actually interested in
```

Maybe an additional utility function could do this job?

**Comment by FurkanToprak** [comment]
I understand your dilemma. While you could fork my code and publish your own private npm package, I don't believe that is necessary. Instead, consider doing the following:

1) Extract out the relevant attribute from your objects.
2) Get the BM25 scores of these documents.
3) Sort the score array and the object array in parallel.

By doing this, you'll reach a very similar level of efficiency as my code. Though you will have to iterate through your object array once more, asymptotically it will be the same efficiency.

Thanks again for your input. Please contact me if you have any more questions.
